server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # SPA: qualquer rota que não seja um arquivo estático cai no index.html (Angular Router
    # resolve client-side a partir daí).
    location / {
        try_files $uri $uri/ /index.html;
    }
}
